//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS3AudioBot.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TS3AudioBot.Localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 This feature is not documented. 的本地化字符串。
        /// </summary>
        internal static string _undocumented {
            get {
                return ResourceManager.GetString("_undocumented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adds a new song to the queue. 的本地化字符串。
        /// </summary>
        internal static string cmd_add_help {
            get {
                return ResourceManager.GetString("cmd_add_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creates a new command alias. 的本地化字符串。
        /// </summary>
        internal static string cmd_alias_add_help {
            get {
                return ResourceManager.GetString("cmd_alias_add_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lists all currently registered alias. 的本地化字符串。
        /// </summary>
        internal static string cmd_alias_list_help {
            get {
                return ResourceManager.GetString("cmd_alias_list_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removes an existing alias. 的本地化字符串。
        /// </summary>
        internal static string cmd_alias_remove_help {
            get {
                return ResourceManager.GetString("cmd_alias_remove_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shows the implementation of the alias. 的本地化字符串。
        /// </summary>
        internal static string cmd_alias_show_help {
            get {
                return ResourceManager.GetString("cmd_alias_show_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generates an api token. 的本地化字符串。
        /// </summary>
        internal static string cmd_api_token_help {
            get {
                return ResourceManager.GetString("cmd_api_token_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clears the avatar of the bot. 的本地化字符串。
        /// </summary>
        internal static string cmd_bot_avatar_clear_help {
            get {
                return ResourceManager.GetString("cmd_bot_avatar_clear_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sets an avatar for the bot 的本地化字符串。
        /// </summary>
        internal static string cmd_bot_avatar_set_help {
            get {
                return ResourceManager.GetString("cmd_bot_avatar_set_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set your bot a badge. The badges string starts with &apos;overwolf=0:badges=&apos; 的本地化字符串。
        /// </summary>
        internal static string cmd_bot_badges_help {
            get {
                return ResourceManager.GetString("cmd_bot_badges_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moves the bot to your channel. 的本地化字符串。
        /// </summary>
        internal static string cmd_bot_come_help {
            get {
                return ResourceManager.GetString("cmd_bot_come_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets the status of the channel commander mode. 的本地化字符串。
        /// </summary>
        internal static string cmd_bot_commander_help {
            get {
                return ResourceManager.GetString("cmd_bot_commander_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disables channel commander. 的本地化字符串。
        /// </summary>
        internal static string cmd_bot_commander_off_help {
            get {
                return ResourceManager.GetString("cmd_bot_commander_off_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enables channel commander. 的本地化字符串。
        /// </summary>
        internal static string cmd_bot_commander_on_help {
            get {
                return ResourceManager.GetString("cmd_bot_commander_on_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connects a new bot with the settings from the template name. 的本地化字符串。
        /// </summary>
        internal static string cmd_bot_connect_template_help {
            get {
                return ResourceManager.GetString("cmd_bot_connect_template_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connects a new bot to the given address. 的本地化字符串。
        /// </summary>
        internal static string cmd_bot_connect_to_help {
            get {
                return ResourceManager.GetString("cmd_bot_connect_to_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sets the description of the bot. 的本地化字符串。
        /// </summary>
        internal static string cmd_bot_description_set_help {
            get {
                return ResourceManager.GetString("cmd_bot_description_set_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop this bot instance. 的本地化字符串。
        /// </summary>
        internal static string cmd_bot_disconnect_help {
            get {
                return ResourceManager.GetString("cmd_bot_disconnect_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets various information about the bot. 的本地化字符串。
        /// </summary>
        internal static string cmd_bot_info_help {
            get {
                return ResourceManager.GetString("cmd_bot_info_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets the id of the current bot. 的本地化字符串。
        /// </summary>
        internal static string cmd_bot_info_id_help {
            get {
                return ResourceManager.GetString("cmd_bot_info_id_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets a list of all active bots. 的本地化字符串。
        /// </summary>
        internal static string cmd_bot_list_help {
            get {
                return ResourceManager.GetString("cmd_bot_list_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moves the bot to you or a specified channel. 的本地化字符串。
        /// </summary>
        internal static string cmd_bot_move_help {
            get {
                return ResourceManager.GetString("cmd_bot_move_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gives the bot a new name. 的本地化字符串。
        /// </summary>
        internal static string cmd_bot_name_help {
            get {
                return ResourceManager.GetString("cmd_bot_name_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saves the configuration for the newly connected bot. 的本地化字符串。
        /// </summary>
        internal static string cmd_bot_save_help {
            get {
                return ResourceManager.GetString("cmd_bot_save_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bot setup failed. See logs for more details. 的本地化字符串。
        /// </summary>
        internal static string cmd_bot_setup_error {
            get {
                return ResourceManager.GetString("cmd_bot_setup_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sets all teamspeak rights for the bot to be fully functional. 的本地化字符串。
        /// </summary>
        internal static string cmd_bot_setup_help {
            get {
                return ResourceManager.GetString("cmd_bot_setup_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switches the context to the requested bot. 的本地化字符串。
        /// </summary>
        internal static string cmd_bot_use_help {
            get {
                return ResourceManager.GetString("cmd_bot_use_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removes all songs from the current playlist. 的本地化字符串。
        /// </summary>
        internal static string cmd_clear_help {
            get {
                return ResourceManager.GetString("cmd_clear_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Executes a given command or string 的本地化字符串。
        /// </summary>
        internal static string cmd_eval_help {
            get {
                return ResourceManager.GetString("cmd_eval_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets all information about you. 的本地化字符串。
        /// </summary>
        internal static string cmd_getmy_all_help {
            get {
                return ResourceManager.GetString("cmd_getmy_all_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets your channel id you are currently in. 的本地化字符串。
        /// </summary>
        internal static string cmd_getmy_channel_help {
            get {
                return ResourceManager.GetString("cmd_getmy_channel_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets your database id. 的本地化字符串。
        /// </summary>
        internal static string cmd_getmy_dbid_help {
            get {
                return ResourceManager.GetString("cmd_getmy_dbid_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets your id. 的本地化字符串。
        /// </summary>
        internal static string cmd_getmy_id_help {
            get {
                return ResourceManager.GetString("cmd_getmy_id_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets your nickname. 的本地化字符串。
        /// </summary>
        internal static string cmd_getmy_name_help {
            get {
                return ResourceManager.GetString("cmd_getmy_name_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets your unique id. 的本地化字符串。
        /// </summary>
        internal static string cmd_getmy_uid_help {
            get {
                return ResourceManager.GetString("cmd_getmy_uid_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets all information about a user, searching with his id. 的本地化字符串。
        /// </summary>
        internal static string cmd_getuser_all_byid_help {
            get {
                return ResourceManager.GetString("cmd_getuser_all_byid_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets all information of a user, searching with his name. 的本地化字符串。
        /// </summary>
        internal static string cmd_getuser_all_byname_help {
            get {
                return ResourceManager.GetString("cmd_getuser_all_byname_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets the channel id a user is currently in, searching with his id. 的本地化字符串。
        /// </summary>
        internal static string cmd_getuser_channel_byid_help {
            get {
                return ResourceManager.GetString("cmd_getuser_channel_byid_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets the database id of a user, searching with his id. 的本地化字符串。
        /// </summary>
        internal static string cmd_getuser_dbid_byid_help {
            get {
                return ResourceManager.GetString("cmd_getuser_dbid_byid_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets the id of a user, searching with his name. 的本地化字符串。
        /// </summary>
        internal static string cmd_getuser_id_byname_help {
            get {
                return ResourceManager.GetString("cmd_getuser_id_byname_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets the user name by dbid, searching with his database id. 的本地化字符串。
        /// </summary>
        internal static string cmd_getuser_name_bydbid_help {
            get {
                return ResourceManager.GetString("cmd_getuser_name_bydbid_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets the nickname of a user, searching with his id. 的本地化字符串。
        /// </summary>
        internal static string cmd_getuser_name_byid_help {
            get {
                return ResourceManager.GetString("cmd_getuser_name_byid_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets the unique id of a user, searching with his database id. 的本地化字符串。
        /// </summary>
        internal static string cmd_getuser_uid_bydbid_help {
            get {
                return ResourceManager.GetString("cmd_getuser_uid_bydbid_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets the unique id of a user, searching with his id. 的本地化字符串。
        /// </summary>
        internal static string cmd_getuser_uid_byid_help {
            get {
                return ResourceManager.GetString("cmd_getuser_uid_byid_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Requested command is ambiguous between: {0} 的本地化字符串。
        /// </summary>
        internal static string cmd_help_error_ambiguous_command {
            get {
                return ResourceManager.GetString("cmd_help_error_ambiguous_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The command has no further subfunctions after {0} 的本地化字符串。
        /// </summary>
        internal static string cmd_help_error_no_further_subfunctions {
            get {
                return ResourceManager.GetString("cmd_help_error_no_further_subfunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No matching command found! Try !help to get a list of all commands. 的本地化字符串。
        /// </summary>
        internal static string cmd_help_error_no_matching_command {
            get {
                return ResourceManager.GetString("cmd_help_error_no_matching_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seems like something went wrong. No help can be shown for this command path. 的本地化字符串。
        /// </summary>
        internal static string cmd_help_error_unknown_error {
            get {
                return ResourceManager.GetString("cmd_help_error_unknown_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ========= Welcome to the TS3AudioBot =========
        ///If you need any help with a special command use !help &lt;commandName&gt;.
        ///Here are all possible commands: 的本地化字符串。
        /// </summary>
        internal static string cmd_help_header {
            get {
                return ResourceManager.GetString("cmd_help_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shows all commands or detailed help about a specific command. 的本地化字符串。
        /// </summary>
        internal static string cmd_help_help {
            get {
                return ResourceManager.GetString("cmd_help_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The command contains the following subfunctions: {0} 的本地化字符串。
        /// </summary>
        internal static string cmd_help_info_contains_subfunctions {
            get {
                return ResourceManager.GetString("cmd_help_info_contains_subfunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;id&gt; Adds the song with &lt;id&gt; to the queue 的本地化字符串。
        /// </summary>
        internal static string cmd_history_add_help {
            get {
                return ResourceManager.GetString("cmd_history_add_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do want to clean the history file now?  的本地化字符串。
        /// </summary>
        internal static string cmd_history_clean_confirm_clean {
            get {
                return ResourceManager.GetString("cmd_history_clean_confirm_clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cleans up the history file for better startup performance. 的本地化字符串。
        /// </summary>
        internal static string cmd_history_clean_help {
            get {
                return ResourceManager.GetString("cmd_history_clean_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do want to remove all defective links file now? 的本地化字符串。
        /// </summary>
        internal static string cmd_history_clean_removedefective_confirm_clean {
            get {
                return ResourceManager.GetString("cmd_history_clean_removedefective_confirm_clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checks for all links in the history which cannot be opened anymore and removes them. 的本地化字符串。
        /// </summary>
        internal static string cmd_history_clean_removedefective_help {
            get {
                return ResourceManager.GetString("cmd_history_clean_removedefective_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you really want to delete the entry &quot;{0}&quot;
        ///with the id {1}? 的本地化字符串。
        /// </summary>
        internal static string cmd_history_delete_confirm {
            get {
                return ResourceManager.GetString("cmd_history_delete_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;id&gt; Removes the entry with &lt;id&gt; from the history 的本地化字符串。
        /// </summary>
        internal static string cmd_history_delete_help {
            get {
                return ResourceManager.GetString("cmd_history_delete_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets the last &lt;count&gt; songs from the user with the given &lt;user-dbid&gt; 的本地化字符串。
        /// </summary>
        internal static string cmd_history_from_help {
            get {
                return ResourceManager.GetString("cmd_history_from_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is the currently highest song id. 的本地化字符串。
        /// </summary>
        internal static string cmd_history_id_last {
            get {
                return ResourceManager.GetString("cmd_history_id_last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} will be the next song id. 的本地化字符串。
        /// </summary>
        internal static string cmd_history_id_next {
            get {
                return ResourceManager.GetString("cmd_history_id_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (last|next) Gets the highest|next song id 的本地化字符串。
        /// </summary>
        internal static string cmd_history_id_string_help {
            get {
                return ResourceManager.GetString("cmd_history_id_string_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;id&gt; Displays all saved informations about the song with &lt;id&gt; 的本地化字符串。
        /// </summary>
        internal static string cmd_history_id_uint_help {
            get {
                return ResourceManager.GetString("cmd_history_id_uint_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plays the last song again 的本地化字符串。
        /// </summary>
        internal static string cmd_history_last_help {
            get {
                return ResourceManager.GetString("cmd_history_last_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;count&gt; Gets the last &lt;count&gt; played songs. 的本地化字符串。
        /// </summary>
        internal static string cmd_history_last_int_help {
            get {
                return ResourceManager.GetString("cmd_history_last_int_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no song in the history. 的本地化字符串。
        /// </summary>
        internal static string cmd_history_last_is_empty {
            get {
                return ResourceManager.GetString("cmd_history_last_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;id&gt; Playes the song with &lt;id&gt; 的本地化字符串。
        /// </summary>
        internal static string cmd_history_play_help {
            get {
                return ResourceManager.GetString("cmd_history_play_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;id&gt; &lt;name&gt; Sets the name of the song with &lt;id&gt; to &lt;name&gt; 的本地化字符串。
        /// </summary>
        internal static string cmd_history_rename_help {
            get {
                return ResourceManager.GetString("cmd_history_rename_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The new name must not be empty or only whitespaces. 的本地化字符串。
        /// </summary>
        internal static string cmd_history_rename_invalid_name {
            get {
                return ResourceManager.GetString("cmd_history_rename_invalid_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;date&gt; Gets all songs played until &lt;date&gt;. 的本地化字符串。
        /// </summary>
        internal static string cmd_history_till_DateTime_help {
            get {
                return ResourceManager.GetString("cmd_history_till_DateTime_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;name&gt; Any of those desciptors: (hour|today|yesterday|week) 的本地化字符串。
        /// </summary>
        internal static string cmd_history_till_string_help {
            get {
                return ResourceManager.GetString("cmd_history_till_string_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets all songs which title contains &lt;string&gt; 的本地化字符串。
        /// </summary>
        internal static string cmd_history_title_help {
            get {
                return ResourceManager.GetString("cmd_history_title_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conditionally executes subcommands. 的本地化字符串。
        /// </summary>
        internal static string cmd_if_help {
            get {
                return ResourceManager.GetString("cmd_if_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown comparison operator. 的本地化字符串。
        /// </summary>
        internal static string cmd_if_unknown_operator {
            get {
                return ResourceManager.GetString("cmd_if_unknown_operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show&apos;s a small summary of the current playlist and queue status. 的本地化字符串。
        /// </summary>
        internal static string cmd_info_help {
            get {
                return ResourceManager.GetString("cmd_info_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allows you to combine multiple JsonResults into one 的本地化字符串。
        /// </summary>
        internal static string cmd_json_merge_help {
            get {
                return ResourceManager.GetString("cmd_json_merge_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jumps to the requested index in the current queue and starts playing. 的本地化字符串。
        /// </summary>
        internal static string cmd_jump_help {
            get {
                return ResourceManager.GetString("cmd_jump_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Guess what? 的本地化字符串。
        /// </summary>
        internal static string cmd_kickme_help {
            get {
                return ResourceManager.GetString("cmd_kickme_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I&apos;m not strong enough, master! 的本地化字符串。
        /// </summary>
        internal static string cmd_kickme_missing_permission {
            get {
                return ResourceManager.GetString("cmd_kickme_missing_permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets a link to the origin of the current song. 的本地化字符串。
        /// </summary>
        internal static string cmd_link_help {
            get {
                return ResourceManager.GetString("cmd_link_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;id&gt; Adds a link to your private playlist from the history by &lt;id&gt;. 的本地化字符串。
        /// </summary>
        internal static string cmd_list_add_help {
            get {
                return ResourceManager.GetString("cmd_list_add_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clears a playlist. 的本地化字符串。
        /// </summary>
        internal static string cmd_list_clear_help {
            get {
                return ResourceManager.GetString("cmd_list_clear_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are not allowed to delete others playlists. 的本地化字符串。
        /// </summary>
        internal static string cmd_list_delete_cannot_delete_others_playlist {
            get {
                return ResourceManager.GetString("cmd_list_delete_cannot_delete_others_playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you really want to delete the playlist &quot;{0}&quot;? 的本地化字符串。
        /// </summary>
        internal static string cmd_list_delete_confirm {
            get {
                return ResourceManager.GetString("cmd_list_delete_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;name&gt; Deletes the playlist with the name &lt;name&gt;. You can only delete playlists which you also have created. Admins can delete every playlist. 的本地化字符串。
        /// </summary>
        internal static string cmd_list_delete_help {
            get {
                return ResourceManager.GetString("cmd_list_delete_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;link&gt; Imports a playlist form an other platform like youtube etc. 的本地化字符串。
        /// </summary>
        internal static string cmd_list_get_help {
            get {
                return ResourceManager.GetString("cmd_list_get_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;index&gt; Removes the item at &lt;index&gt;. 的本地化字符串。
        /// </summary>
        internal static string cmd_list_item_delete_help {
            get {
                return ResourceManager.GetString("cmd_list_item_delete_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;from&gt; &lt;to&gt; Moves a item in a playlist &lt;from&gt; &lt;to&gt; position. 的本地化字符串。
        /// </summary>
        internal static string cmd_list_item_move_help {
            get {
                return ResourceManager.GetString("cmd_list_item_move_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Renames an item. 的本地化字符串。
        /// </summary>
        internal static string cmd_list_item_name_help {
            get {
                return ResourceManager.GetString("cmd_list_item_name_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Displays all available playlists from all users. 的本地化字符串。
        /// </summary>
        internal static string cmd_list_list_help {
            get {
                return ResourceManager.GetString("cmd_list_list_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opens a playlist to be editable for you. This replaces your current worklist with the opened playlist. 的本地化字符串。
        /// </summary>
        internal static string cmd_list_load_help {
            get {
                return ResourceManager.GetString("cmd_list_load_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaded &quot;{0}&quot; with {1} songs. 的本地化字符串。
        /// </summary>
        internal static string cmd_list_load_response {
            get {
                return ResourceManager.GetString("cmd_list_load_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Appends another playlist to yours. 的本地化字符串。
        /// </summary>
        internal static string cmd_list_merge_help {
            get {
                return ResourceManager.GetString("cmd_list_merge_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Displays the name of the playlist you are currently working on. 的本地化字符串。
        /// </summary>
        internal static string cmd_list_name_help {
            get {
                return ResourceManager.GetString("cmd_list_name_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replaces the current freelist with your workinglist and plays from the beginning. 的本地化字符串。
        /// </summary>
        internal static string cmd_list_play_help {
            get {
                return ResourceManager.GetString("cmd_list_play_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Appends your playlist to the freelist. 的本地化字符串。
        /// </summary>
        internal static string cmd_list_queue_help {
            get {
                return ResourceManager.GetString("cmd_list_queue_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stores your current workinglist to disk. 的本地化字符串。
        /// </summary>
        internal static string cmd_list_save_help {
            get {
                return ResourceManager.GetString("cmd_list_save_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Playlist: &quot;{0}&quot; with {1} songs. 的本地化字符串。
        /// </summary>
        internal static string cmd_list_show_header {
            get {
                return ResourceManager.GetString("cmd_list_show_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;name&gt; Displays all songs currently in the playlists with the name &lt;name&gt; 的本地化字符串。
        /// </summary>
        internal static string cmd_list_show_help {
            get {
                return ResourceManager.GetString("cmd_list_show_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plays the next song in the playlist. 的本地化字符串。
        /// </summary>
        internal static string cmd_next_help {
            get {
                return ResourceManager.GetString("cmd_next_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Displays the AST of the requested command. 的本地化字符串。
        /// </summary>
        internal static string cmd_parse_command_help {
            get {
                return ResourceManager.GetString("cmd_parse_command_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Well, pauses the song. Undo with !play. 的本地化字符串。
        /// </summary>
        internal static string cmd_pause_help {
            get {
                return ResourceManager.GetString("cmd_pause_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically tries to decide whether the link is a special resource (like youtube) or a direct resource (like ./hello.mp3) and starts it. 的本地化字符串。
        /// </summary>
        internal static string cmd_play_help {
            get {
                return ResourceManager.GetString("cmd_play_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lists all found plugins. 的本地化字符串。
        /// </summary>
        internal static string cmd_plugin_list_help {
            get {
                return ResourceManager.GetString("cmd_plugin_list_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unloads a plugin. 的本地化字符串。
        /// </summary>
        internal static string cmd_plugin_load_help {
            get {
                return ResourceManager.GetString("cmd_plugin_load_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unloads a plugin. 的本地化字符串。
        /// </summary>
        internal static string cmd_plugin_unload_help {
            get {
                return ResourceManager.GetString("cmd_plugin_unload_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Requests a private session with the ServerBot so you can be intimate. 的本地化字符串。
        /// </summary>
        internal static string cmd_pm_help {
            get {
                return ResourceManager.GetString("cmd_pm_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hi {0} 的本地化字符串。
        /// </summary>
        internal static string cmd_pm_hi {
            get {
                return ResourceManager.GetString("cmd_pm_hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Writes a message to a particular user. 的本地化字符串。
        /// </summary>
        internal static string cmd_pm_user_help {
            get {
                return ResourceManager.GetString("cmd_pm_user_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plays the previous song in the playlist. 的本地化字符串。
        /// </summary>
        internal static string cmd_previous_help {
            get {
                return ResourceManager.GetString("cmd_previous_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lets you format multiple parameter to one. 的本地化字符串。
        /// </summary>
        internal static string cmd_print_help {
            get {
                return ResourceManager.GetString("cmd_print_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Displays the current play queue. 的本地化字符串。
        /// </summary>
        internal static string cmd_queue_help {
            get {
                return ResourceManager.GetString("cmd_queue_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you really want to quit? 的本地化字符串。
        /// </summary>
        internal static string cmd_quit_confirm {
            get {
                return ResourceManager.GetString("cmd_quit_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Closes the TS3AudioBot application. 的本地化字符串。
        /// </summary>
        internal static string cmd_quit_help {
            get {
                return ResourceManager.GetString("cmd_quit_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shows the quizmode status. 的本地化字符串。
        /// </summary>
        internal static string cmd_quiz_help {
            get {
                return ResourceManager.GetString("cmd_quiz_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable to show the songnames again. 的本地化字符串。
        /// </summary>
        internal static string cmd_quiz_off_help {
            get {
                return ResourceManager.GetString("cmd_quiz_off_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No cheating! Everybody has to see it! 的本地化字符串。
        /// </summary>
        internal static string cmd_quiz_off_no_cheating {
            get {
                return ResourceManager.GetString("cmd_quiz_off_no_cheating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable to hide the songnames and let your friends guess the title. 的本地化字符串。
        /// </summary>
        internal static string cmd_quiz_on_help {
            get {
                return ResourceManager.GetString("cmd_quiz_on_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets whether or not to play playlists in random order. 的本地化字符串。
        /// </summary>
        internal static string cmd_random_help {
            get {
                return ResourceManager.GetString("cmd_random_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disables random playlist playback 的本地化字符串。
        /// </summary>
        internal static string cmd_random_off_help {
            get {
                return ResourceManager.GetString("cmd_random_off_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enables random playlist playback 的本地化字符串。
        /// </summary>
        internal static string cmd_random_on_help {
            get {
                return ResourceManager.GetString("cmd_random_on_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets the unique seed for a certain playback order 的本地化字符串。
        /// </summary>
        internal static string cmd_random_seed_help {
            get {
                return ResourceManager.GetString("cmd_random_seed_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sets the unique seed for a certain playback order 的本地化字符串。
        /// </summary>
        internal static string cmd_random_seed_int_help {
            get {
                return ResourceManager.GetString("cmd_random_seed_int_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only letters allowed. 的本地化字符串。
        /// </summary>
        internal static string cmd_random_seed_only_letters_allowed {
            get {
                return ResourceManager.GetString("cmd_random_seed_only_letters_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sets the unique seed for a certain playback order 的本地化字符串。
        /// </summary>
        internal static string cmd_random_seed_string_help {
            get {
                return ResourceManager.GetString("cmd_random_seed_string_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repeats the entire playlist. 的本地化字符串。
        /// </summary>
        internal static string cmd_repeat_all_help {
            get {
                return ResourceManager.GetString("cmd_repeat_all_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets the current repeat mode. 的本地化字符串。
        /// </summary>
        internal static string cmd_repeat_help {
            get {
                return ResourceManager.GetString("cmd_repeat_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repeating the playlist. 的本地化字符串。
        /// </summary>
        internal static string cmd_repeat_info_all {
            get {
                return ResourceManager.GetString("cmd_repeat_info_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not repeating. 的本地化字符串。
        /// </summary>
        internal static string cmd_repeat_info_off {
            get {
                return ResourceManager.GetString("cmd_repeat_info_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repeating a single song. 的本地化字符串。
        /// </summary>
        internal static string cmd_repeat_info_one {
            get {
                return ResourceManager.GetString("cmd_repeat_info_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disables repeating. 的本地化字符串。
        /// </summary>
        internal static string cmd_repeat_off_help {
            get {
                return ResourceManager.GetString("cmd_repeat_off_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repeats a single song. 的本地化字符串。
        /// </summary>
        internal static string cmd_repeat_one_help {
            get {
                return ResourceManager.GetString("cmd_repeat_one_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Returns the subset of allowed commands the caller (you) can execute. 的本地化字符串。
        /// </summary>
        internal static string cmd_rights_can_help {
            get {
                return ResourceManager.GetString("cmd_rights_can_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error while parsing file, see log for more details. 的本地化字符串。
        /// </summary>
        internal static string cmd_rights_reload_error_parsing_file {
            get {
                return ResourceManager.GetString("cmd_rights_reload_error_parsing_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reloads the rights configuration from file. 的本地化字符串。
        /// </summary>
        internal static string cmd_rights_reload_help {
            get {
                return ResourceManager.GetString("cmd_rights_reload_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets a random number. 的本地化字符串。
        /// </summary>
        internal static string cmd_rng_help {
            get {
                return ResourceManager.GetString("cmd_rng_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value must be 0 or positive. 的本地化字符串。
        /// </summary>
        internal static string cmd_rng_value_must_be_positive {
            get {
                return ResourceManager.GetString("cmd_rng_value_must_be_positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found the following songs. Use &quot;{0}&quot; to play. Use &quot;{1}&quot; to queue. 的本地化字符串。
        /// </summary>
        internal static string cmd_search_header {
            get {
                return ResourceManager.GetString("cmd_search_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found no results for this query. 的本地化字符串。
        /// </summary>
        internal static string cmd_search_no_result {
            get {
                return ResourceManager.GetString("cmd_search_no_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jumps to a timemark within the current song. 的本地化字符串。
        /// </summary>
        internal static string cmd_seek_help {
            get {
                return ResourceManager.GetString("cmd_seek_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The time was not in a correct format, see !help seek for more information. 的本地化字符串。
        /// </summary>
        internal static string cmd_seek_invalid_format {
            get {
                return ResourceManager.GetString("cmd_seek_invalid_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The point of time is not within the song length. 的本地化字符串。
        /// </summary>
        internal static string cmd_seek_out_of_range {
            get {
                return ResourceManager.GetString("cmd_seek_out_of_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selects a song from a previous search and plays it. 的本地化字符串。
        /// </summary>
        internal static string cmd_select_help {
            get {
                return ResourceManager.GetString("cmd_select_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reloads the bot template configuration from the file. 的本地化字符串。
        /// </summary>
        internal static string cmd_settings_bot_reload_help {
            get {
                return ResourceManager.GetString("cmd_settings_bot_reload_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicates a bot template with a new name. 的本地化字符串。
        /// </summary>
        internal static string cmd_settings_copy_help {
            get {
                return ResourceManager.GetString("cmd_settings_copy_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creates a new bot template. 的本地化字符串。
        /// </summary>
        internal static string cmd_settings_create_help {
            get {
                return ResourceManager.GetString("cmd_settings_create_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deletes a bot template. 的本地化字符串。
        /// </summary>
        internal static string cmd_settings_delete_help {
            get {
                return ResourceManager.GetString("cmd_settings_delete_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please specify a key. E.g {0} 的本地化字符串。
        /// </summary>
        internal static string cmd_settings_empty_usage {
            get {
                return ResourceManager.GetString("cmd_settings_empty_usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets a value from the bot settings. 的本地化字符串。
        /// </summary>
        internal static string cmd_settings_get_help {
            get {
                return ResourceManager.GetString("cmd_settings_get_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets a value from the core settings. 的本地化字符串。
        /// </summary>
        internal static string cmd_settings_global_get_help {
            get {
                return ResourceManager.GetString("cmd_settings_global_get_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set a value from the core settings. 的本地化字符串。
        /// </summary>
        internal static string cmd_settings_global_set_help {
            get {
                return ResourceManager.GetString("cmd_settings_global_set_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Provides get/set methods to change the settings. 的本地化字符串。
        /// </summary>
        internal static string cmd_settings_help {
            get {
                return ResourceManager.GetString("cmd_settings_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get the desciption for a setting. 的本地化字符串。
        /// </summary>
        internal static string cmd_settings_help_help {
            get {
                return ResourceManager.GetString("cmd_settings_help_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reloads the core configuration from the file. 的本地化字符串。
        /// </summary>
        internal static string cmd_settings_reload_help {
            get {
                return ResourceManager.GetString("cmd_settings_reload_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sets a value from the bot settings. 的本地化字符串。
        /// </summary>
        internal static string cmd_settings_set_help {
            get {
                return ResourceManager.GetString("cmd_settings_set_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tells you the name of the current song. 的本地化字符串。
        /// </summary>
        internal static string cmd_song_help {
            get {
                return ResourceManager.GetString("cmd_song_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets the length and position of the current track. 的本地化字符串。
        /// </summary>
        internal static string cmd_song_position_help {
            get {
                return ResourceManager.GetString("cmd_song_position_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stops the current song. 的本地化字符串。
        /// </summary>
        internal static string cmd_stop_help {
            get {
                return ResourceManager.GetString("cmd_stop_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adds your current channel to the music playback. 的本地化字符串。
        /// </summary>
        internal static string cmd_subscribe_channel_help {
            get {
                return ResourceManager.GetString("cmd_subscribe_channel_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subscribes the specified client to listen from anywhere 的本地化字符串。
        /// </summary>
        internal static string cmd_subscribe_client_help {
            get {
                return ResourceManager.GetString("cmd_subscribe_client_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lets you hear the music independent from the channel you are in. 的本地化字符串。
        /// </summary>
        internal static string cmd_subscribe_help {
            get {
                return ResourceManager.GetString("cmd_subscribe_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adds your current channel to the music playback. 的本地化字符串。
        /// </summary>
        internal static string cmd_subscribe_tempchannel_help {
            get {
                return ResourceManager.GetString("cmd_subscribe_tempchannel_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Take a substring from a string. 的本地化字符串。
        /// </summary>
        internal static string cmd_take_help {
            get {
                return ResourceManager.GetString("cmd_take_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not enough arguments to take. 的本地化字符串。
        /// </summary>
        internal static string cmd_take_not_enough_arguements {
            get {
                return ResourceManager.GetString("cmd_take_not_enough_arguements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removes your current channel from the music playback. 的本地化字符串。
        /// </summary>
        internal static string cmd_unsubscribe_channel_help {
            get {
                return ResourceManager.GetString("cmd_unsubscribe_channel_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsubscribes the specified client to listen from anywhere. 的本地化字符串。
        /// </summary>
        internal static string cmd_unsubscribe_client_help {
            get {
                return ResourceManager.GetString("cmd_unsubscribe_client_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only lets you hear the music in active channels again. 的本地化字符串。
        /// </summary>
        internal static string cmd_unsubscribe_help {
            get {
                return ResourceManager.GetString("cmd_unsubscribe_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clears all temporary targets. 的本地化字符串。
        /// </summary>
        internal static string cmd_unsubscribe_temporary_help {
            get {
                return ResourceManager.GetString("cmd_unsubscribe_temporary_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets the current build version. 的本地化字符串。
        /// </summary>
        internal static string cmd_version_help {
            get {
                return ResourceManager.GetString("cmd_version_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current volume: {0} 的本地化字符串。
        /// </summary>
        internal static string cmd_volume_current {
            get {
                return ResourceManager.GetString("cmd_volume_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sets the volume level of the music. 的本地化字符串。
        /// </summary>
        internal static string cmd_volume_help {
            get {
                return ResourceManager.GetString("cmd_volume_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Careful you are requesting a very high volume! Do you want to apply this? 的本地化字符串。
        /// </summary>
        internal static string cmd_volume_high_volume_confirm {
            get {
                return ResourceManager.GetString("cmd_volume_high_volume_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The volume level must be between {0} and {1} 的本地化字符串。
        /// </summary>
        internal static string cmd_volume_is_limited {
            get {
                return ResourceManager.GetString("cmd_volume_is_limited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are not allowed to set higher volumes. 的本地化字符串。
        /// </summary>
        internal static string cmd_volume_missing_high_volume_permission {
            get {
                return ResourceManager.GetString("cmd_volume_missing_high_volume_permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The new volume could not be parsed 的本地化字符串。
        /// </summary>
        internal static string cmd_volume_parse_error {
            get {
                return ResourceManager.GetString("cmd_volume_parse_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set how to send music. 的本地化字符串。
        /// </summary>
        internal static string cmd_whisper_all_help {
            get {
                return ResourceManager.GetString("cmd_whisper_all_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set a specific teamspeak whisper group. 的本地化字符串。
        /// </summary>
        internal static string cmd_whisper_group_help {
            get {
                return ResourceManager.GetString("cmd_whisper_group_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This type requires an additional target. 的本地化字符串。
        /// </summary>
        internal static string cmd_whisper_group_missing_target {
            get {
                return ResourceManager.GetString("cmd_whisper_group_missing_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This type does not take an additional target. 的本地化字符串。
        /// </summary>
        internal static string cmd_whisper_group_superfluous_target {
            get {
                return ResourceManager.GetString("cmd_whisper_group_superfluous_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currently targeting: 的本地化字符串。
        /// </summary>
        internal static string cmd_whisper_list_header {
            get {
                return ResourceManager.GetString("cmd_whisper_list_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set how to send music. 的本地化字符串。
        /// </summary>
        internal static string cmd_whisper_list_help {
            get {
                return ResourceManager.GetString("cmd_whisper_list_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nowhere! 的本地化字符串。
        /// </summary>
        internal static string cmd_whisper_list_target_none {
            get {
                return ResourceManager.GetString("cmd_whisper_list_target_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This channel via voice! 的本地化字符串。
        /// </summary>
        internal static string cmd_whisper_list_target_voice {
            get {
                return ResourceManager.GetString("cmd_whisper_list_target_voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Channel 的本地化字符串。
        /// </summary>
        internal static string cmd_whisper_list_target_whisper_channel {
            get {
                return ResourceManager.GetString("cmd_whisper_list_target_whisper_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clients 的本地化字符串。
        /// </summary>
        internal static string cmd_whisper_list_target_whisper_clients {
            get {
                return ResourceManager.GetString("cmd_whisper_list_target_whisper_clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A whisper group {0} {1} ({2})! 的本地化字符串。
        /// </summary>
        internal static string cmd_whisper_list_target_whispergroup {
            get {
                return ResourceManager.GetString("cmd_whisper_list_target_whispergroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enables normal voice mode. 的本地化字符串。
        /// </summary>
        internal static string cmd_whisper_off_help {
            get {
                return ResourceManager.GetString("cmd_whisper_off_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enables default whisper subscription mode. 的本地化字符串。
        /// </summary>
        internal static string cmd_whisper_subscription_help {
            get {
                return ResourceManager.GetString("cmd_whisper_subscription_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Evaluates all parameter. 的本地化字符串。
        /// </summary>
        internal static string cmd_xecute_help {
            get {
                return ResourceManager.GetString("cmd_xecute_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This bot does not exist. 的本地化字符串。
        /// </summary>
        internal static string error_bot_does_not_exist {
            get {
                return ResourceManager.GetString("error_bot_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: {0} 的本地化字符串。
        /// </summary>
        internal static string error_call_error {
            get {
                return ResourceManager.GetString("error_call_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An unexpected error occurred: {0} 的本地化字符串。
        /// </summary>
        internal static string error_call_unexpected_error {
            get {
                return ResourceManager.GetString("error_call_unexpected_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Need at least four arguments to evaluate. 的本地化字符串。
        /// </summary>
        internal static string error_cmd_at_least_four_argument {
            get {
                return ResourceManager.GetString("error_cmd_at_least_four_argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Need at least {0} arguments to evaluate. 的本地化字符串。
        /// </summary>
        internal static string error_cmd_at_least_n_arguments {
            get {
                return ResourceManager.GetString("error_cmd_at_least_n_arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Need at least one argument to evaluate. 的本地化字符串。
        /// </summary>
        internal static string error_cmd_at_least_one_argument {
            get {
                return ResourceManager.GetString("error_cmd_at_least_one_argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Need at least three arguments to evaluate. 的本地化字符串。
        /// </summary>
        internal static string error_cmd_at_least_three_argument {
            get {
                return ResourceManager.GetString("error_cmd_at_least_three_argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Need at least two arguments to evaluate. 的本地化字符串。
        /// </summary>
        internal static string error_cmd_at_least_two_argument {
            get {
                return ResourceManager.GetString("error_cmd_at_least_two_argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The command exceeded the maximum calling complexity. 的本地化字符串。
        /// </summary>
        internal static string error_cmd_complexity_reached {
            get {
                return ResourceManager.GetString("error_cmd_complexity_reached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not convert &quot;{0}&quot; to {1}. 的本地化字符串。
        /// </summary>
        internal static string error_cmd_could_not_convert_to {
            get {
                return ResourceManager.GetString("error_cmd_could_not_convert_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No matching function overload could be found. 的本地化字符串。
        /// </summary>
        internal static string error_cmd_no_matching_overload {
            get {
                return ResourceManager.GetString("error_cmd_no_matching_overload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number is too big. 的本地化字符串。
        /// </summary>
        internal static string error_cmd_number_too_big {
            get {
                return ResourceManager.GetString("error_cmd_number_too_big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found more than one matching key: {0} 的本地化字符串。
        /// </summary>
        internal static string error_config_multiple_keys_found {
            get {
                return ResourceManager.GetString("error_config_multiple_keys_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No config key matching the pattern found. 的本地化字符串。
        /// </summary>
        internal static string error_config_no_key_found {
            get {
                return ResourceManager.GetString("error_config_no_key_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value could not be parsed. 的本地化字符串。
        /// </summary>
        internal static string error_config_value_parse_error {
            get {
                return ResourceManager.GetString("error_config_value_parse_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not create new instance. 的本地化字符串。
        /// </summary>
        internal static string error_could_not_create_bot {
            get {
                return ResourceManager.GetString("error_could_not_create_bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This feature is currently unavailable. 的本地化字符串。
        /// </summary>
        internal static string error_feature_unavailable {
            get {
                return ResourceManager.GetString("error_feature_unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entry could not be stored. 的本地化字符串。
        /// </summary>
        internal static string error_history_could_not_create_entry {
            get {
                return ResourceManager.GetString("error_history_could_not_create_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find entry with this id. 的本地化字符串。
        /// </summary>
        internal static string error_history_could_not_find_entry {
            get {
                return ResourceManager.GetString("error_history_could_not_find_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid token-valid duration. 的本地化字符串。
        /// </summary>
        internal static string error_invalid_token_duration {
            get {
                return ResourceManager.GetString("error_invalid_token_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invoker casted Ghost Walk. 的本地化字符串。
        /// </summary>
        internal static string error_invoker_not_visible {
            get {
                return ResourceManager.GetString("error_invoker_not_visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file still in use. 的本地化字符串。
        /// </summary>
        internal static string error_io_in_use {
            get {
                return ResourceManager.GetString("error_io_in_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The bot does not have the required system permission. 的本地化字符串。
        /// </summary>
        internal static string error_io_missing_permission {
            get {
                return ResourceManager.GetString("error_io_missing_permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An unknown error occoured. 的本地化字符串。
        /// </summary>
        internal static string error_io_unknown_error {
            get {
                return ResourceManager.GetString("error_io_unknown_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The id could not get parsed. 的本地化字符串。
        /// </summary>
        internal static string error_media_failed_to_parse_id {
            get {
                return ResourceManager.GetString("error_media_failed_to_parse_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The resource could not be found. 的本地化字符串。
        /// </summary>
        internal static string error_media_file_not_found {
            get {
                return ResourceManager.GetString("error_media_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No image could not be found. 的本地化字符串。
        /// </summary>
        internal static string error_media_image_not_found {
            get {
                return ResourceManager.GetString("error_media_image_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid or malformed response parts. 的本地化字符串。
        /// </summary>
        internal static string error_media_internal_invalid {
            get {
                return ResourceManager.GetString("error_media_internal_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty or missing response parts. 的本地化字符串。
        /// </summary>
        internal static string error_media_internal_missing {
            get {
                return ResourceManager.GetString("error_media_internal_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The image is invalid. 的本地化字符串。
        /// </summary>
        internal static string error_media_invalid_image {
            get {
                return ResourceManager.GetString("error_media_invalid_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid uri. 的本地化字符串。
        /// </summary>
        internal static string error_media_invalid_uri {
            get {
                return ResourceManager.GetString("error_media_invalid_uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No stream extracted. 的本地化字符串。
        /// </summary>
        internal static string error_media_no_stream_extracted {
            get {
                return ResourceManager.GetString("error_media_no_stream_extracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot execute &apos;{0}&apos;. You are missing the &apos;{1}&apos; right! 的本地化字符串。
        /// </summary>
        internal static string error_missing_right {
            get {
                return ResourceManager.GetString("error_missing_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing session context. 的本地化字符串。
        /// </summary>
        internal static string error_missing_session_context {
            get {
                return ResourceManager.GetString("error_missing_session_context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Request got empty response. 的本地化字符串。
        /// </summary>
        internal static string error_net_empty_response {
            get {
                return ResourceManager.GetString("error_net_empty_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Got error status code. 的本地化字符串。
        /// </summary>
        internal static string error_net_error_status_code {
            get {
                return ResourceManager.GetString("error_net_error_status_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No connection could be established. 的本地化字符串。
        /// </summary>
        internal static string error_net_no_connection {
            get {
                return ResourceManager.GetString("error_net_no_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Request timed out. 的本地化字符串。
        /// </summary>
        internal static string error_net_timeout {
            get {
                return ResourceManager.GetString("error_net_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown request error. 的本地化字符串。
        /// </summary>
        internal static string error_net_unknown {
            get {
                return ResourceManager.GetString("error_net_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No active token found. 的本地化字符串。
        /// </summary>
        internal static string error_no_active_token {
            get {
                return ResourceManager.GetString("error_no_active_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No help found. 的本地化字符串。
        /// </summary>
        internal static string error_no_help {
            get {
                return ResourceManager.GetString("error_no_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No invoker in context. 的本地化字符串。
        /// </summary>
        internal static string error_no_invoker_in_context {
            get {
                return ResourceManager.GetString("error_no_invoker_in_context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing session context. 的本地化字符串。
        /// </summary>
        internal static string error_no_session_in_context {
            get {
                return ResourceManager.GetString("error_no_session_in_context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No target channel found. 的本地化字符串。
        /// </summary>
        internal static string error_no_target_channel {
            get {
                return ResourceManager.GetString("error_no_target_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No teamspeak connection in context. 的本地化字符串。
        /// </summary>
        internal static string error_no_teamspeak_in_context {
            get {
                return ResourceManager.GetString("error_no_teamspeak_in_context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Uid found to register token for. 的本地化字符串。
        /// </summary>
        internal static string error_no_uid_found {
            get {
                return ResourceManager.GetString("error_no_uid_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This command is not available as API. 的本地化字符串。
        /// </summary>
        internal static string error_not_available_from_api {
            get {
                return ResourceManager.GetString("error_not_available_from_api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not found. 的本地化字符串。
        /// </summary>
        internal static string error_not_found {
            get {
                return ResourceManager.GetString("error_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t find a fitting return type to return. 的本地化字符串。
        /// </summary>
        internal static string error_nothing_to_return {
            get {
                return ResourceManager.GetString("error_nothing_to_return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The playlist file is corrupted. Only admins can modify it until fixed. 的本地化字符串。
        /// </summary>
        internal static string error_playlist_broken_file {
            get {
                return ResourceManager.GetString("error_playlist_broken_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot access a playlist which you dont own. 的本地化字符串。
        /// </summary>
        internal static string error_playlist_cannot_access_not_owned {
            get {
                return ResourceManager.GetString("error_playlist_cannot_access_not_owned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nothing to play... 的本地化字符串。
        /// </summary>
        internal static string error_playlist_is_empty {
            get {
                return ResourceManager.GetString("error_playlist_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index must be within playlist length. 的本地化字符串。
        /// </summary>
        internal static string error_playlist_item_index_out_of_range {
            get {
                return ResourceManager.GetString("error_playlist_item_index_out_of_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The name contains invalid characters; please only use [a-zA-Z0-9_-]. 的本地化字符串。
        /// </summary>
        internal static string error_playlist_name_invalid_character {
            get {
                return ResourceManager.GetString("error_playlist_name_invalid_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An empty name is not valid. 的本地化字符串。
        /// </summary>
        internal static string error_playlist_name_invalid_empty {
            get {
                return ResourceManager.GetString("error_playlist_name_invalid_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The name length must be &lt;64. 的本地化字符串。
        /// </summary>
        internal static string error_playlist_name_invalid_too_long {
            get {
                return ResourceManager.GetString("error_playlist_name_invalid_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No playlist directory has been set up. 的本地化字符串。
        /// </summary>
        internal static string error_playlist_no_store_directory {
            get {
                return ResourceManager.GetString("error_playlist_no_store_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The playlist could not be found. 的本地化字符串。
        /// </summary>
        internal static string error_playlist_not_found {
            get {
                return ResourceManager.GetString("error_playlist_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Special list not found. 的本地化字符串。
        /// </summary>
        internal static string error_playlist_special_not_found {
            get {
                return ResourceManager.GetString("error_playlist_special_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Internal error. 的本地化字符串。
        /// </summary>
        internal static string error_playmgr_internal_error {
            get {
                return ResourceManager.GetString("error_playmgr_internal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A few songs failed to start, use {0} to continue. 的本地化字符串。
        /// </summary>
        internal static string error_playmgr_many_songs_failed {
            get {
                return ResourceManager.GetString("error_playmgr_many_songs_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugin error: {0} 的本地化字符串。
        /// </summary>
        internal static string error_plugin_error {
            get {
                return ResourceManager.GetString("error_plugin_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not load. 的本地化字符串。
        /// </summary>
        internal static string error_resfac_could_not_load {
            get {
                return ResourceManager.GetString("error_resfac_could_not_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Considered multiple factories but all failed. 的本地化字符串。
        /// </summary>
        internal static string error_resfac_multiple_factories_failed {
            get {
                return ResourceManager.GetString("error_resfac_multiple_factories_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No registered factory for &quot;{0}&quot; found. 的本地化字符串。
        /// </summary>
        internal static string error_resfac_no_registered_factory {
            get {
                return ResourceManager.GetString("error_resfac_no_registered_factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nothing to select... 的本地化字符串。
        /// </summary>
        internal static string error_select_empty {
            get {
                return ResourceManager.GetString("error_select_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot move there. 的本地化字符串。
        /// </summary>
        internal static string error_ts_cannot_move {
            get {
                return ResourceManager.GetString("error_ts_cannot_move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot set commander mode. 的本地化字符串。
        /// </summary>
        internal static string error_ts_cannot_set_commander {
            get {
                return ResourceManager.GetString("error_ts_cannot_set_commander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing teamspeak permissions. 的本地化字符串。
        /// </summary>
        internal static string error_ts_code_2568 {
            get {
                return ResourceManager.GetString("error_ts_code_2568", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid channel password. 的本地化字符串。
        /// </summary>
        internal static string error_ts_code_781 {
            get {
                return ResourceManager.GetString("error_ts_code_781", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Teamspeak Error: {0} 的本地化字符串。
        /// </summary>
        internal static string error_ts_error {
            get {
                return ResourceManager.GetString("error_ts_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file to upload is too big. 的本地化字符串。
        /// </summary>
        internal static string error_ts_file_too_big {
            get {
                return ResourceManager.GetString("error_ts_file_too_big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The new name is too long or invalid. 的本地化字符串。
        /// </summary>
        internal static string error_ts_invalid_name {
            get {
                return ResourceManager.GetString("error_ts_invalid_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The message to send is longer than the allowed maximum. 的本地化字符串。
        /// </summary>
        internal static string error_ts_msg_too_long {
            get {
                return ResourceManager.GetString("error_ts_msg_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No client found. 的本地化字符串。
        /// </summary>
        internal static string error_ts_no_client_found {
            get {
                return ResourceManager.GetString("error_ts_no_client_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown Teamspeak Error. 的本地化字符串。
        /// </summary>
        internal static string error_ts_unknown_error {
            get {
                return ResourceManager.GetString("error_ts_unknown_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized descriptor. 的本地化字符串。
        /// </summary>
        internal static string error_unrecognized_descriptor {
            get {
                return ResourceManager.GetString("error_unrecognized_descriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please use this command in a private session. 的本地化字符串。
        /// </summary>
        internal static string error_use_private {
            get {
                return ResourceManager.GetString("error_use_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your value is out of range. Select one between {0} and {1}. 的本地化字符串。
        /// </summary>
        internal static string error_value_not_in_range {
            get {
                return ResourceManager.GetString("error_value_not_in_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No youtube-dl response 的本地化字符串。
        /// </summary>
        internal static string error_ytdl_empty_response {
            get {
                return ResourceManager.GetString("error_ytdl_empty_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to run youtube-dl. 的本地化字符串。
        /// </summary>
        internal static string error_ytdl_failed_to_run {
            get {
                return ResourceManager.GetString("error_ytdl_failed_to_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Youtube-Dl could not be found. The song/video cannot be played due to restrictions. 的本地化字符串。
        /// </summary>
        internal static string error_ytdl_not_found {
            get {
                return ResourceManager.GetString("error_ytdl_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 youtube-dl failed to load the resource. 的本地化字符串。
        /// </summary>
        internal static string error_ytdl_song_failed_to_load {
            get {
                return ResourceManager.GetString("error_ytdl_song_failed_to_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This might take a while and make the bot unresponsive in meanwhile. 的本地化字符串。
        /// </summary>
        internal static string info_bot_might_be_unresponsive {
            get {
                return ResourceManager.GetString("info_bot_might_be_unresponsive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Quiztime!&gt; 的本地化字符串。
        /// </summary>
        internal static string info_botstatus_quiztime {
            get {
                return ResourceManager.GetString("info_botstatus_quiztime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Sleeping&gt; 的本地化字符串。
        /// </summary>
        internal static string info_botstatus_sleeping {
            get {
                return ResourceManager.GetString("info_botstatus_sleeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cleanup done! 的本地化字符串。
        /// </summary>
        internal static string info_cleanup_done {
            get {
                return ResourceManager.GetString("info_cleanup_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is nothing on right now... 的本地化字符串。
        /// </summary>
        internal static string info_currently_not_playing {
            get {
                return ResourceManager.GetString("info_currently_not_playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Now playing: {0} 的本地化字符串。
        /// </summary>
        internal static string info_currently_playing {
            get {
                return ResourceManager.GetString("info_currently_playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;empty&gt; 的本地化字符串。
        /// </summary>
        internal static string info_empty {
            get {
                return ResourceManager.GetString("info_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 number 的本地化字符串。
        /// </summary>
        internal static string info_number {
            get {
                return ResourceManager.GetString("info_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 off 的本地化字符串。
        /// </summary>
        internal static string info_off {
            get {
                return ResourceManager.GetString("info_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ok 的本地化字符串。
        /// </summary>
        internal static string info_ok {
            get {
                return ResourceManager.GetString("info_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 on 的本地化字符串。
        /// </summary>
        internal static string info_on {
            get {
                return ResourceManager.GetString("info_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No next song could be played. 的本地化字符串。
        /// </summary>
        internal static string info_playmgr_no_next_song {
            get {
                return ResourceManager.GetString("info_playmgr_no_next_song", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No previous song could be played. 的本地化字符串。
        /// </summary>
        internal static string info_playmgr_no_previous_song {
            get {
                return ResourceManager.GetString("info_playmgr_no_previous_song", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorry, you have to guess! 的本地化字符串。
        /// </summary>
        internal static string info_quizmode_is_active {
            get {
                return ResourceManager.GetString("info_quizmode_is_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removed &quot;{0}&quot; 的本地化字符串。
        /// </summary>
        internal static string info_removed {
            get {
                return ResourceManager.GetString("info_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Channel commander is {0} 的本地化字符串。
        /// </summary>
        internal static string info_status_channelcommander {
            get {
                return ResourceManager.GetString("info_status_channelcommander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quizmode is {0} 的本地化字符串。
        /// </summary>
        internal static string info_status_quizmode {
            get {
                return ResourceManager.GetString("info_status_quizmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Random is {0} 的本地化字符串。
        /// </summary>
        internal static string info_status_random {
            get {
                return ResourceManager.GetString("info_status_random", resourceCulture);
            }
        }
    }
}
